version: '3'

services:
    db:
        image: mysql:5.5
        container_name: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: teste1234
        volumes:
          - mysql_data:/var/lib/mysql
        ports:
          - "3306:3306"
volumes:
  mysql_data: 