FROM ubuntu

ENV http_proxy http://192.168.1.1:3128
ENV https_proxy http://192.168.1.1:3128

RUN apt-get update && apt-get install -y --no-install-recommends apache2 libapache2-mod-jk git

EXPOSE 80 443

ENTRYPOINT ["apache2ctl", "-D", "FOREGROUND"]